### ISSUE TITLE
Newly Added Images create an attachment page and appear on the Attachment Sitemap

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/search-index-purge#54] opened 2018-06-27 20:18 UTC
When I install the Purge plugin I was expecting that only the current attachment pages would appear on the attachment sitemap. 

Any future images would not create attachment pages which then appear on the sitemap. 

Yet they do. 

### Steps to Reproduce

**1.Install Purge Plugin**

**2.Add an image file and create attachment page**

![screen_shot_2018-06-27_at_4_11_23_pm](https://user-images.githubusercontent.com/8238074/41997275-854060be-7a25-11e8-9d1b-635c0284a6d4.png)

**3.Embed it on a post/page**

![screen shot 2018-06-27 at 4 17 11 pm](https://user-images.githubusercontent.com/8238074/41997294-8f8f205a-7a25-11e8-9ca0-bd057dc8f7df.png)

**4.See the new attachment page appear on the attachment sitemap**

![4](https://user-images.githubusercontent.com/8238074/41997317-9d0a5ec0-7a25-11e8-99e3-da192d37eec3.png)

**5.Clicking on it throws the 410**

![screen shot 2018-06-27 at 4 17 53 pm](https://user-images.githubusercontent.com/8238074/41997335-ae92c11e-7a25-11e8-8b8d-22823b701744.png)

**Tech Specs**
Yoast SEO: v7.7.1
Yoast SEO: Search index purge: 1.0

**Comment by benvaassen** [comment] 2018-06-28 08:12
Duplicate of https://github.com/Yoast/search-index-purge/issues/48 which already has a fix. Will be released in 1.1.

**Closed** 2018-06-28 08:13 UTC
Labels: support
